### ISSUE TITLE
Zoom to points not working

### ISSUE THREAD

**Issue by taran03** [msamwill/CMV_Widgets#1]
Thanks for sharing your work.  This is a nice and useful tool! However, I can't seem to get it to zoom to point feature records returned in the results grid.  I can successfully zoom to selected polygon features from the grid. Any suggestions why the point zoom to is failing? Thanks again.

**Comment by taran03** [comment]
This is resolved, thanks.

**Comment by msamwill** [comment]
Would you mind sharing what you did to resolve it?  I have not yet tested points in my application.

**Comment by taran03** [comment]
I updated the Search.js file to your most current release. Apparently, I was working with an older file from which the console was showing an error on line 363 of the js file. 

This works:
 if (geometry.x && geometry.y) 

This did not:
 if (feature.geometry.x && feature.geometry.y)

I have now tested with points, lines and polygons and all work fine. Thanks again for sharing this.

**Comment by msamwill** [comment]
Okay good.  Thanks!
